USE PinballFX_ranking;

	INSERT INTO Player(Pseudo) VALUES ('[TSW] Quant');
INSERT INTO Team (NAME) VALUES ('Team Enhancer');	INSERT INTO Player(Pseudo, team_id) VALUES ('Adlegeek59 [Team Enhancer]',(SELECT ID FROM TEAM WHERE NAME = 'Team Enhancer'));
	INSERT INTO Player(Pseudo) VALUES ('adler1mhk');
	INSERT INTO Player(Pseudo) VALUES ('Admiral Crunch');
	INSERT INTO Player(Pseudo) VALUES ('admiralackbar111');
	INSERT INTO Player(Pseudo) VALUES ('Aegylon');
	INSERT INTO Player(Pseudo) VALUES ('AgentLloyd');
	INSERT INTO Player(Pseudo) VALUES ('akos_chios');
	INSERT INTO Player(Pseudo) VALUES ('Alex');
	INSERT INTO Player(Pseudo) VALUES ('Alf007-alpha2');
	INSERT INTO Player(Pseudo) VALUES ('allenkeyz');
	INSERT INTO Player(Pseudo) VALUES ('Amberjax');
	INSERT INTO Player(Pseudo) VALUES ('Anaicapito');
	INSERT INTO Player(Pseudo) VALUES ('AnkouDu44');
	INSERT INTO Player(Pseudo) VALUES ('Antaiseito');
	INSERT INTO Player(Pseudo) VALUES ('Anthony');
	INSERT INTO Player(Pseudo) VALUES ('Arcturus');
	INSERT INTO Player(Pseudo) VALUES ('Ariophene');
	INSERT INTO Player(Pseudo) VALUES ('ArtCore-NL');
	INSERT INTO Player(Pseudo) VALUES ('articulo-cubica0');
	INSERT INTO Player(Pseudo) VALUES ('Aurelie_jp');
	INSERT INTO Player(Pseudo) VALUES ('AverageSnow1100');
	INSERT INTO Player(Pseudo) VALUES ('Ayala272');
	INSERT INTO Player(Pseudo) VALUES ('Baalbalan');
	INSERT INTO Player(Pseudo) VALUES ('Bad Doggyy');
	INSERT INTO Player(Pseudo) VALUES ('Badgerfan70');
	INSERT INTO Player(Pseudo) VALUES ('bangsutan8tion');
	INSERT INTO Player(Pseudo) VALUES ('Baptiti');
	INSERT INTO Player(Pseudo) VALUES ('barfridgepsb');
	INSERT INTO Player(Pseudo) VALUES ('Batfink-ENG-76');
	INSERT INTO Player(Pseudo) VALUES ('BeerMeJesus');
	INSERT INTO Player(Pseudo) VALUES ('BelugaFox');
INSERT INTO Team (NAME) VALUES ('Team Flipper VR');	INSERT INTO Player(Pseudo, team_id) VALUES ('Benoit XII [Team Flipper VR]',(SELECT ID FROM TEAM WHERE NAME = 'Team Flipper VR'));
	INSERT INTO Player(Pseudo) VALUES ('BeyondAtlantis');
	INSERT INTO Player(Pseudo) VALUES ('Bierbold');
	INSERT INTO Player(Pseudo) VALUES ('biomachinist');
	INSERT INTO Player(Pseudo) VALUES ('bj00rn');
	INSERT INTO Player(Pseudo) VALUES ('BlueCrayon77');
	INSERT INTO Player(Pseudo) VALUES ('BobkoRage 79');
	INSERT INTO Player(Pseudo) VALUES ('Boergerking');
	INSERT INTO Player(Pseudo) VALUES ('boulibaye7518');
	INSERT INTO Player(Pseudo) VALUES ('bowlingman88');
	INSERT INTO Player(Pseudo) VALUES ('briki2049');
	INSERT INTO Player(Pseudo) VALUES ('Bruno');
	INSERT INTO Player(Pseudo) VALUES ('BurningHarvest');
	INSERT INTO Player(Pseudo) VALUES ('C89');
	INSERT INTO Player(Pseudo) VALUES ('cacaboudinus');
INSERT INTO Team (NAME) VALUES ('Team Enhancer');	INSERT INTO Player(Pseudo, team_id) VALUES ('Caius C+ [Team Enhancer]',(SELECT ID FROM TEAM WHERE NAME = 'Team Enhancer'));
	INSERT INTO Player(Pseudo) VALUES ('Camel Tokyo');
	INSERT INTO Player(Pseudo) VALUES ('CANDLEASS');
	INSERT INTO Player(Pseudo) VALUES ('castle024');
	INSERT INTO Player(Pseudo) VALUES ('CATCH M A T Z E');
	INSERT INTO Player(Pseudo) VALUES ('Caucasianred');
	INSERT INTO Player(Pseudo) VALUES ('Cave Canem @ Zerberus');
	INSERT INTO Player(Pseudo) VALUES ('Chip_Skunk');
	INSERT INTO Player(Pseudo) VALUES ('chipzilla');
	INSERT INTO Player(Pseudo) VALUES ('Ciclon');
	INSERT INTO Player(Pseudo) VALUES ('ClipperSnapper01');
	INSERT INTO Player(Pseudo) VALUES ('COLLSY');
	INSERT INTO Player(Pseudo) VALUES ('courtlaw');
	INSERT INTO Player(Pseudo) VALUES ('Craze316');
	INSERT INTO Player(Pseudo) VALUES ('Crazy Newt');
	INSERT INTO Player(Pseudo) VALUES ('Crow Continuum');
	INSERT INTO Player(Pseudo) VALUES ('Crystal Beach Arcade');
	INSERT INTO Player(Pseudo) VALUES ('CYBERPUNK 87 ');
	INSERT INTO Player(Pseudo) VALUES ('CyboMan');
	INSERT INTO Player(Pseudo) VALUES ('D1x13Fl4tl1n3');
	INSERT INTO Player(Pseudo) VALUES ('Dal420');
	INSERT INTO Player(Pseudo) VALUES ('Daley_Pinball');
	INSERT INTO Player(Pseudo) VALUES ('Darkendone');
	INSERT INTO Player(Pseudo) VALUES ('DayDreamer80');
	INSERT INTO Player(Pseudo) VALUES ('de la Nae');
	INSERT INTO Player(Pseudo) VALUES ('DeathCombat');
	INSERT INTO Player(Pseudo) VALUES ('deep_nib90');
	INSERT INTO Player(Pseudo) VALUES ('Demonic');
	INSERT INTO Player(Pseudo) VALUES ('Depatsfan64');
	INSERT INTO Player(Pseudo) VALUES ('Der Pate');
	INSERT INTO Player(Pseudo) VALUES ('desmeijster1');
	INSERT INTO Player(Pseudo) VALUES ('DeviousOne34');
	INSERT INTO Player(Pseudo) VALUES ('Diceman');
	INSERT INTO Player(Pseudo) VALUES ('Dicentim');
	INSERT INTO Player(Pseudo) VALUES ('Digger_Blue');
	INSERT INTO Player(Pseudo) VALUES ('Dinjoralo');
	INSERT INTO Player(Pseudo) VALUES ('DitzyRobert');
	INSERT INTO Player(Pseudo) VALUES ('djhoffi2014');
	INSERT INTO Player(Pseudo) VALUES ('DNKTHATSH559');
	INSERT INTO Player(Pseudo) VALUES ('Donald Trump QQ');
	INSERT INTO Player(Pseudo) VALUES ('dookieagain');
	INSERT INTO Player(Pseudo) VALUES ('Dr. Jan Itor');
	INSERT INTO Player(Pseudo) VALUES ('Dr.KNO');
	INSERT INTO Player(Pseudo) VALUES ('dragon_lapin1');
	INSERT INTO Player(Pseudo) VALUES ('Drake Stardragon');
	INSERT INTO Player(Pseudo) VALUES ('DrFeelgood');
	INSERT INTO Player(Pseudo) VALUES ('DrMachtogonapus');
	INSERT INTO Player(Pseudo) VALUES ('DSOLO777');
	INSERT INTO Player(Pseudo) VALUES ('duane229');
	INSERT INTO Player(Pseudo) VALUES ('el_gecko83');
	INSERT INTO Player(Pseudo) VALUES ('ElNino77');
	INSERT INTO Player(Pseudo) VALUES ('ematamusic');
	INSERT INTO Player(Pseudo) VALUES ('Emuser');
	INSERT INTO Player(Pseudo) VALUES ('EndZeit72');
	INSERT INTO Player(Pseudo) VALUES ('Enthusiast');
	INSERT INTO Player(Pseudo) VALUES ('epsilon828');
	INSERT INTO Player(Pseudo) VALUES ('erik8181');
	INSERT INTO Player(Pseudo) VALUES ('Erlastor');
	INSERT INTO Player(Pseudo) VALUES ('Essnem');
	INSERT INTO Player(Pseudo) VALUES ('Extrema22');
	INSERT INTO Player(Pseudo) VALUES ('F3F3-_64Fr');
	INSERT INTO Player(Pseudo) VALUES ('feisty-netting42');
	INSERT INTO Player(Pseudo) VALUES ('FerraroFinn');
INSERT INTO Team (NAME) VALUES ('TFFT Pinball');	INSERT INTO Player(Pseudo, team_id) VALUES ('FischersMethod',(SELECT ID FROM TEAM WHERE NAME = 'TFFT Pinball'));
	INSERT INTO Player(Pseudo) VALUES ('Fishmonger');
	INSERT INTO Player(Pseudo) VALUES ('Flippa');
	INSERT INTO Player(Pseudo) VALUES ('Flipper VR');
	INSERT INTO Player(Pseudo) VALUES ('Fluffy_McDuffee');
	INSERT INTO Player(Pseudo) VALUES ('foofaraw and Chiquita(ARF!)');
	INSERT INTO Player(Pseudo) VALUES ('formatt');
	INSERT INTO Player(Pseudo) VALUES ('FoxyLoxy');
	INSERT INTO Player(Pseudo) VALUES ('gamer_natez');
	INSERT INTO Player(Pseudo) VALUES ('Gantuss');
	INSERT INTO Player(Pseudo) VALUES ('GARCIA LUPs');
	INSERT INTO Player(Pseudo) VALUES ('GentleGiant');
	INSERT INTO Player(Pseudo) VALUES ('geronimoingame');
	INSERT INTO Player(Pseudo) VALUES ('gerthein');
	INSERT INTO Player(Pseudo) VALUES ('Gonzy74');
	INSERT INTO Player(Pseudo) VALUES ('GoodbyeJeff');
	INSERT INTO Player(Pseudo) VALUES ('GregStanbury');
	INSERT INTO Player(Pseudo) VALUES ('Grim_Metallic');
	INSERT INTO Player(Pseudo) VALUES ('Guarez');
	INSERT INTO Player(Pseudo) VALUES ('HackSkY59');
	INSERT INTO Player(Pseudo) VALUES ('Harley_Breakout');
	INSERT INTO Player(Pseudo) VALUES ('Harry Rasing');
	INSERT INTO Player(Pseudo) VALUES ('Haruka');
	INSERT INTO Player(Pseudo) VALUES ('Hashisian');
	INSERT INTO Player(Pseudo) VALUES ('Headset');
INSERT INTO Team (NAME) VALUES ('The International Pinball Team');	INSERT INTO Player(Pseudo, team_id) VALUES ('Helder Scroll',(SELECT ID FROM TEAM WHERE NAME = 'The International Pinball Team'));
	INSERT INTO Player(Pseudo) VALUES ('heldermarco');
	INSERT INTO Player(Pseudo) VALUES ('HencoWish');
	INSERT INTO Player(Pseudo) VALUES ('Heureka 19');
	INSERT INTO Player(Pseudo) VALUES ('Hilmahaha');
	INSERT INTO Player(Pseudo) VALUES ('hirnklopper');
	INSERT INTO Player(Pseudo) VALUES ('Horde Commander');
	INSERT INTO Player(Pseudo) VALUES ('Hulk 585');
	INSERT INTO Player(Pseudo) VALUES ('idkkev');
	INSERT INTO Player(Pseudo) VALUES ('illmaniackiller');
	INSERT INTO Player(Pseudo) VALUES ('IndianaJonesing');
	INSERT INTO Player(Pseudo) VALUES ('J4k3 Ry4n');
	INSERT INTO Player(Pseudo) VALUES ('Jammin Jace');
	INSERT INTO Player(Pseudo) VALUES ('jaredmorgs');
	INSERT INTO Player(Pseudo) VALUES ('Jarego');
	INSERT INTO Player(Pseudo) VALUES ('Jarrodski');
	INSERT INTO Player(Pseudo) VALUES ('jason');
	INSERT INTO Player(Pseudo) VALUES ('JDS Sonic95');
	INSERT INTO Player(Pseudo) VALUES ('Jefferson');
INSERT INTO Team (NAME) VALUES ('Team Flipper VR');	INSERT INTO Player(Pseudo, team_id) VALUES ('Jerry [Team Flipper VR]',(SELECT ID FROM TEAM WHERE NAME = 'Team Flipper VR'));
	INSERT INTO Player(Pseudo) VALUES ('Jmak909');
	INSERT INTO Player(Pseudo) VALUES ('Jockel451');
	INSERT INTO Player(Pseudo) VALUES ('jonny41');
	INSERT INTO Player(Pseudo) VALUES ('Jonowar1');
	INSERT INTO Player(Pseudo) VALUES ('josefbacher50');
	INSERT INTO Player(Pseudo) VALUES ('Joselz');
	INSERT INTO Player(Pseudo) VALUES ('joshiewilham');
	INSERT INTO Player(Pseudo) VALUES ('jowpinball69');
	INSERT INTO Player(Pseudo) VALUES ('JP3196');
	INSERT INTO Player(Pseudo) VALUES ('JUNKER Gibson');
	INSERT INTO Player(Pseudo) VALUES ('JustMonkeyD1');
	INSERT INTO Player(Pseudo) VALUES ('kappy1966');
	INSERT INTO Player(Pseudo) VALUES ('Karinou72');
	INSERT INTO Player(Pseudo) VALUES ('Katapultator_666');
	INSERT INTO Player(Pseudo) VALUES ('Katatonia');
	INSERT INTO Player(Pseudo) VALUES ('kay989');
	INSERT INTO Player(Pseudo) VALUES ('kdecgp');
	INSERT INTO Player(Pseudo) VALUES ('KeliBali');
	INSERT INTO Player(Pseudo) VALUES ('KillaZap');
	INSERT INTO Player(Pseudo) VALUES ('KindFawn1161929');
	INSERT INTO Player(Pseudo) VALUES ('Kleig_Karath');
	INSERT INTO Player(Pseudo) VALUES ('Kosmic King');
	INSERT INTO Player(Pseudo) VALUES ('Krakehz');
	INSERT INTO Player(Pseudo) VALUES ('LallunaBlanca');
	INSERT INTO Player(Pseudo) VALUES ('Leander.quest');
	INSERT INTO Player(Pseudo) VALUES ('legendaryXatdX');
	INSERT INTO Player(Pseudo) VALUES ('lila-Duft');
	INSERT INTO Player(Pseudo) VALUES ('linne_zen');
	INSERT INTO Player(Pseudo) VALUES ('lokiss88');
	INSERT INTO Player(Pseudo) VALUES ('LostInTheAether');
	INSERT INTO Player(Pseudo) VALUES ('Loup2588');
	INSERT INTO Player(Pseudo) VALUES ('Lu');
	INSERT INTO Player(Pseudo) VALUES ('luckeyslev');
	INSERT INTO Player(Pseudo) VALUES ('LuigiSi92');
	INSERT INTO Player(Pseudo) VALUES ('Luppe Lupeteus');
	INSERT INTO Player(Pseudo) VALUES ('m11');
	INSERT INTO Player(Pseudo) VALUES ('Madkeno');
	INSERT INTO Player(Pseudo) VALUES ('Mafia210');
	INSERT INTO Player(Pseudo) VALUES ('MAgnumPeelEye');
	INSERT INTO Player(Pseudo) VALUES ('magrog2219');
	INSERT INTO Player(Pseudo) VALUES ('Malarkeyness');
	INSERT INTO Player(Pseudo) VALUES ('MarcellinoTerzo');
	INSERT INTO Player(Pseudo) VALUES ('Marcus');
	INSERT INTO Player(Pseudo) VALUES ('marine_4twenty');
	INSERT INTO Player(Pseudo) VALUES ('Matt Beeching');
	INSERT INTO Player(Pseudo) VALUES ('Matthew006248');
	INSERT INTO Player(Pseudo) VALUES ('Matzomek');
	INSERT INTO Player(Pseudo) VALUES ('Mellow_Doom');
	INSERT INTO Player(Pseudo) VALUES ('mentary44');
	INSERT INTO Player(Pseudo) VALUES ('Mercyscene');
	INSERT INTO Player(Pseudo) VALUES ('mhk555');
	INSERT INTO Player(Pseudo) VALUES ('MIami_357');
	INSERT INTO Player(Pseudo) VALUES ('Michel Boulon [Team Boulon]');
	INSERT INTO Player(Pseudo) VALUES ('Michelangelo');
	INSERT INTO Player(Pseudo) VALUES ('Mickey019');
	INSERT INTO Player(Pseudo) VALUES ('MicrowaceDeath');
	INSERT INTO Player(Pseudo) VALUES ('Mind Boggling');
	INSERT INTO Player(Pseudo) VALUES ('MindOfTimes');
	INSERT INTO Player(Pseudo) VALUES ('mistaCombs');
	INSERT INTO Player(Pseudo) VALUES ('mister19a');
	INSERT INTO Player(Pseudo) VALUES ('mloellgen');
	INSERT INTO Player(Pseudo) VALUES ('Monsterkind689');
	INSERT INTO Player(Pseudo) VALUES ('moose');
	INSERT INTO Player(Pseudo) VALUES ('More Guiness');
	INSERT INTO Player(Pseudo) VALUES ('Mr.Jackson');
	INSERT INTO Player(Pseudo) VALUES ('MrCatch77');
	INSERT INTO Player(Pseudo) VALUES ('mxforth');
	INSERT INTO Player(Pseudo) VALUES ('My2sons');
	INSERT INTO Player(Pseudo) VALUES ('MythDrake');
	INSERT INTO Player(Pseudo) VALUES ('NakBak');
	INSERT INTO Player(Pseudo) VALUES ('Nathall');
	INSERT INTO Player(Pseudo) VALUES ('nclearblack');
	INSERT INTO Player(Pseudo) VALUES ('Nerner6869');
	INSERT INTO Player(Pseudo) VALUES ('NichtdieMama2202');
	INSERT INTO Player(Pseudo) VALUES ('nick917');
	INSERT INTO Player(Pseudo) VALUES ('nikomugerdi');
	INSERT INTO Player(Pseudo) VALUES ('Ninjasage');
	INSERT INTO Player(Pseudo) VALUES ('nosenager');
	INSERT INTO Player(Pseudo) VALUES ('nulldepict');
	INSERT INTO Player(Pseudo) VALUES ('obrad1717');
	INSERT INTO Player(Pseudo) VALUES ('ohvi');
	INSERT INTO Player(Pseudo) VALUES ('oldfortytwo');
	INSERT INTO Player(Pseudo) VALUES ('Ömmes');
	INSERT INTO Player(Pseudo) VALUES ('Ondrez');
	INSERT INTO Player(Pseudo) VALUES ('Opperschaap');
	INSERT INTO Player(Pseudo) VALUES ('OttOBuS');
	INSERT INTO Player(Pseudo) VALUES ('p-menke');
	INSERT INTO Player(Pseudo) VALUES ('Panam-game');
	INSERT INTO Player(Pseudo) VALUES ('papapablito');
	INSERT INTO Player(Pseudo) VALUES ('papysoupape');
	INSERT INTO Player(Pseudo) VALUES ('patrikimmerstein');
	INSERT INTO Player(Pseudo) VALUES ('Paydro2208');
	INSERT INTO Player(Pseudo) VALUES ('pemato66');
	INSERT INTO Player(Pseudo) VALUES ('PeterSong_');
	INSERT INTO Player(Pseudo) VALUES ('petrosmaria');
	INSERT INTO Player(Pseudo) VALUES ('pezima77');
	INSERT INTO Player(Pseudo) VALUES ('PGH_Mike79');
	INSERT INTO Player(Pseudo) VALUES ('phatwayne');
	INSERT INTO Player(Pseudo) VALUES ('Pinballwiz45b');
	INSERT INTO Player(Pseudo) VALUES ('pinhondje');
	INSERT INTO Player(Pseudo) VALUES ('pmicw58');
	INSERT INTO Player(Pseudo) VALUES ('Poison');
	INSERT INTO Player(Pseudo) VALUES ('Poltergeist619');
	INSERT INTO Player(Pseudo) VALUES ('Pomor PL');
	INSERT INTO Player(Pseudo) VALUES ('Pop Sergeant');
	INSERT INTO Player(Pseudo) VALUES ('Pops');
	INSERT INTO Player(Pseudo) VALUES ('Pseudo-Indispo');
	INSERT INTO Player(Pseudo) VALUES ('Pungeance');
	INSERT INTO Player(Pseudo) VALUES ('Qiyamah');
	INSERT INTO Player(Pseudo) VALUES ('RAP487X');
	INSERT INTO Player(Pseudo) VALUES ('RaphonR');
	INSERT INTO Player(Pseudo) VALUES ('ravenfinland');
	INSERT INTO Player(Pseudo) VALUES ('Rbwings2');
	INSERT INTO Player(Pseudo) VALUES ('ReD_EyE_jEDi79');
	INSERT INTO Player(Pseudo) VALUES ('Ref Jeff');
	INSERT INTO Player(Pseudo) VALUES ('Retr0gamerGR');
	INSERT INTO Player(Pseudo) VALUES ('Ribsta34');
	INSERT INTO Player(Pseudo) VALUES ('richc111');
	INSERT INTO Player(Pseudo) VALUES ('ripd1');
	INSERT INTO Player(Pseudo) VALUES ('ROBOinthezone TwitchYoutube');
	INSERT INTO Player(Pseudo) VALUES ('ROBSTER85');
	INSERT INTO Player(Pseudo) VALUES ('RolisterYT');
	INSERT INTO Player(Pseudo) VALUES ('Ronna 666');
	INSERT INTO Player(Pseudo) VALUES ('RoundHouseRob');
	INSERT INTO Player(Pseudo) VALUES ('rousey13');
	INSERT INTO Player(Pseudo) VALUES ('Router87');
	INSERT INTO Player(Pseudo) VALUES ('Roxoror');
	INSERT INTO Player(Pseudo) VALUES ('royesk');
	INSERT INTO Player(Pseudo) VALUES ('RuboMontana');
	INSERT INTO Player(Pseudo) VALUES ('Rulp');
	INSERT INTO Player(Pseudo) VALUES ('Ryan');
	INSERT INTO Player(Pseudo) VALUES ('Ryroby1');
	INSERT INTO Player(Pseudo) VALUES ('safridou');
	INSERT INTO Player(Pseudo) VALUES ('SaltyColt413754');
	INSERT INTO Player(Pseudo) VALUES ('SANPET02');
	INSERT INTO Player(Pseudo) VALUES ('SavouryTub203');
	INSERT INTO Player(Pseudo) VALUES ('schelmi 59');
	INSERT INTO Player(Pseudo) VALUES ('Schijnheiligste');
	INSERT INTO Player(Pseudo) VALUES ('Schimsen');
	INSERT INTO Player(Pseudo) VALUES ('schlemi 59');
	INSERT INTO Player(Pseudo) VALUES ('Schrodingers God');
	INSERT INTO Player(Pseudo) VALUES ('senter');
	INSERT INTO Player(Pseudo) VALUES ('sgraffiottolo');
	INSERT INTO Player(Pseudo) VALUES ('ShadowXOR');
	INSERT INTO Player(Pseudo) VALUES ('Sheran U Odal');
	INSERT INTO Player(Pseudo) VALUES ('Shrodingers God');
	INSERT INTO Player(Pseudo) VALUES ('Sir Rudolf');
	INSERT INTO Player(Pseudo) VALUES ('SixxColt');
	INSERT INTO Player(Pseudo) VALUES ('Skyrider1279');
	INSERT INTO Player(Pseudo) VALUES ('Slayerdon');
	INSERT INTO Player(Pseudo) VALUES ('sma1359');
	INSERT INTO Player(Pseudo) VALUES ('SMerrell»');
	INSERT INTO Player(Pseudo) VALUES ('Snowman-DSX');
	INSERT INTO Player(Pseudo) VALUES ('sonictonic72');
	INSERT INTO Player(Pseudo) VALUES ('spambulance');
	INSERT INTO Player(Pseudo) VALUES ('Spërdo Spardaj');
	INSERT INTO Player(Pseudo) VALUES ('SpiegelErde');
	INSERT INTO Player(Pseudo) VALUES ('Spoutnut');
	INSERT INTO Player(Pseudo) VALUES ('stardevil1970');
	INSERT INTO Player(Pseudo) VALUES ('stefan');
	INSERT INTO Player(Pseudo) VALUES ('stevo');
	INSERT INTO Player(Pseudo) VALUES ('STORM-ANIMAL-1');
	INSERT INTO Player(Pseudo) VALUES ('Strano');
	INSERT INTO Player(Pseudo) VALUES ('Sub-zero12473');
	INSERT INTO Player(Pseudo) VALUES ('Tame_Pounce');
	INSERT INTO Player(Pseudo) VALUES ('TazDad132');
	INSERT INTO Player(Pseudo) VALUES ('The Swayze Express');
	INSERT INTO Player(Pseudo) VALUES ('THE_INKSPOT');
	INSERT INTO Player(Pseudo) VALUES ('The_Jack_1967089');
	INSERT INTO Player(Pseudo) VALUES ('thegermwar');
	INSERT INTO Player(Pseudo) VALUES ('ThorSynthZ');
	INSERT INTO Player(Pseudo) VALUES ('Tim');
	INSERT INTO Player(Pseudo) VALUES ('tomtomgo25');
	INSERT INTO Player(Pseudo) VALUES ('tondagossa');
	INSERT INTO Player(Pseudo) VALUES ('TonyTomcatF14');
	INSERT INTO Player(Pseudo) VALUES ('tOp1At');
	INSERT INTO Player(Pseudo) VALUES ('Torfa');
	INSERT INTO Player(Pseudo) VALUES ('Tracebustin');
	INSERT INTO Player(Pseudo) VALUES ('TritiumLUPsClub');
	INSERT INTO Player(Pseudo) VALUES ('TuttiDeLeon');
	INSERT INTO Player(Pseudo) VALUES ('TVs Frank');
	INSERT INTO Player(Pseudo) VALUES ('Umbrella');
	INSERT INTO Player(Pseudo) VALUES ('UndoingChip2665');
	INSERT INTO Player(Pseudo) VALUES ('utd4000');
	INSERT INTO Player(Pseudo) VALUES ('V_Lecavelier24');
	INSERT INTO Player(Pseudo) VALUES ('V1ctorSalgado');
	INSERT INTO Player(Pseudo) VALUES ('V2Console');
	INSERT INTO Player(Pseudo) VALUES ('Vicente Luis');
	INSERT INTO Player(Pseudo) VALUES ('Video');
	INSERT INTO Player(Pseudo) VALUES ('vidrackar');
	INSERT INTO Player(Pseudo) VALUES ('Vincente Luis');
	INSERT INTO Player(Pseudo) VALUES ('vlayken');
	INSERT INTO Player(Pseudo) VALUES ('Wariacik');
INSERT INTO Team (NAME) VALUES ('LUPs Wizard Team');	INSERT INTO Player(Pseudo, team_id) VALUES ('WimS [LuPsClub]',(SELECT ID FROM TEAM WHERE NAME = 'LUPs Wizard Team'));
	INSERT INTO Player(Pseudo) VALUES ('Wintercat47s');
	INSERT INTO Player(Pseudo) VALUES ('Xx-Hulk77-xX');
	INSERT INTO Player(Pseudo) VALUES ('XxGabrielxX');
	INSERT INTO Player(Pseudo) VALUES ('yermin5000');
INSERT INTO Team (NAME) VALUES ('Team Enhancer');	INSERT INTO Player(Pseudo, team_id) VALUES ('Yesai [Team Enhancer]',(SELECT ID FROM TEAM WHERE NAME = 'Team Enhancer'));
	INSERT INTO Player(Pseudo) VALUES ('Zen BirdMan');
	INSERT INTO Player(Pseudo) VALUES ('Zeron');
	INSERT INTO Player(Pseudo) VALUES ('Zeyrox');
	INSERT INTO Player(Pseudo) VALUES ('ZOGSLAYER');
	INSERT INTO Player(Pseudo) VALUES ('Zombie moan');
	INSERT INTO Player(Pseudo) VALUES ('zwielbelkowski');